#!/usr/bin/env bash
#Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
#!/bin/bash

pidfile="/var/run/myscript.pid"
handle_sigterm() {
    echo "I hate the kill command"
    cleanup_and_exit
}
handle_sigint() {
    echo "Y U no love me?!"
}
handle_sigquit() {
    echo "Received SIGQUIT. Cleaning up and terminating..."
    cleanup_and_exit
}
cleanup_and_exit() {
    rm -f "$pidfile"
    exit 0
}

trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

echo $$ > "$pidfile"
echo "To infinity and beyond indefinitely"

while true; do
    sleep 2
done
