#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
min="0"
hour="0"
i="0"
while [ "$i" -lt 70 ];do
	if(("$min" == "0")); then
		echo "Hour: $hour"
	else
		echo "$min"
	fi

	if(("$min" != "59")); then
		((min++))
	else
		min="0"
		((hour++))
	fi

		((i++))
done
