#!/usr/bin/env bash
#Bash script that configures an Ubuntu server
#facebook.com resolves to 8.8.8.8
#localhost resolves to 127.0.0.2
cp /etc/hosts /etc/hosts.old
sudo echo "8.8.8.8	facebook.com" >> /etc/hosts.old
CMD ["sed", "-i", "s/127.0.0.1/127.0.0.2", "/etc/hosts.old"]
cp -f ~/hosts.old /etc/hosts
