#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on.
ip_addresses=$(ifconfig | grep -oP '(?<=inet )(\d+\.\d+\.\d+\.\d+)' | grep -v '127.0.0.1')
echo "$ip_addresses"

